version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/mongodb/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mymongodbUser01!
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  vue-app:
    build:
      context: ./client/
      dockerfile: Dockerfile
    environment:
      - API_BASE_URL="http://backend:8080/search/"
    ports:
      - "8088:80"
volumes:
  mongodb_data: